### ISSUE TITLE
Securing the cluster

### ISSUE THREAD

**Issue by yaniveliash** [quinston/arangodb-kubernetes#1]
Hey,
It seems that the cluster isn't secured as it allow me direct access to it
and doesn't prompt for a password as with single node arangodb instance.

Before deploying the jsons to my kube cluster I did changed the ARANGO_RANDOM_ROOT_PASSWORD
to ARANGO_ROOT_PASSWORD and gave it a static value (I've replaced it in all the occurrences in the various files).

**Comment by quinston** [comment]
Hi!
At the time (around August 2016) I wrote this, I believe ArangoDB said that they explicitly disabled password protection for cluster configurations and recommended that the user secure their clusters from public access by themselves. Have things changed since? I'm not at liberty to test stuff out atm.

**Comment by yaniveliash** [comment]
Cool,
Thanks for the clarification.

I will just secure it internally as advised (in any case it's not ment to be exposed)
